### ISSUE TITLE
How to get audio raw data？

### ISSUE THREAD

**Issue by 980202006** [MZehren/ADTOF#14]

**Comment by 980202006** [comment]
I noticed in the readme that there are audio files in audio/audio, but I didn't find the audio files

**Comment by MZehren** [comment]
The audio files are not included in the repository as I noticed that there are copyrighted tracks I cannot share. If you want to have audio files, you need to use the different scripts presented in the Readme and build a new dataset.

This solution is not optimal and will surely be improved in the future (see https://github.com/MZehren/ADTOF/issues/11#issue-949878671)
