### ISSUE TITLE
Module missing

### ISSUE THREAD

**Issue by HotzingTone** [MZehren/ADTOF#15]
Hello, great thanks for making this dataset!
I couldn't find and install the modules [automix](https://github.com/MZehren/ADTOF/blob/d718bfdc3e03f461f1ea30d005374a48ccd32922/adtof/converters/correctAlignmentConverter.py#L163) specified in [correctAlignmentConverter.py](https://github.com/MZehren/ADTOF/blob/master/adtof/converters/correctAlignmentConverter.py).
Would you please suggest where to download them?
Cheers!

**Comment by MZehren** [comment]
Hello,

It seems that the function calling Automix is a debug function I forgot in the code and is likely deprecated. I would remove the function to correct the issue, or you would have to replace it with your own implementation. But I don't understand how this is an issue since this function is never called.

If you want to install Automix, it is available here: https://github.com/MZehren/Automix. But it is likely outdated compared to the private version I was using. 

Does this help?

**Comment by HotzingTone** [comment]
Hi Mickael,

Thanks for taking the time replying. It does help! And yes you are right, it hasn't been called so far, but I just wanted to make sure all the dependencies are properly installed.

However, I haven't been able to successfully run automaticGrooming.py. The error comes from **madmom** library saying it couldn't load *.ogg files because **ffmpeg** is missing, while in fact ffmpeg is installed. It reads:

`madmom.io.audio.LoadAudioFileError: "All attempts to load audio file 'data/dataset/audio/audio/Pedro Cap - Calma (Remix ft. Farruko).ogg' failed. Try installing ffmpeg (or avconv on Ubuntu Linux)."`

I tried reinstalling `ffmpeg` and `madmom`, but it didn't help. I am using MacOS v12.2.1.

Would you have a guess how to solve this? Thank you so much!

**Comment by MZehren** [comment]
Thank you for your comment.

I did not encounter any issue with FFMPEG personally, but it seems that you are not alone from a quick google search: https://groups.google.com/g/madmom-users/c/xgqHlZuNyIw
Can you try what Sebastian suggests in his answer?

The issue does not come from my ADTOF, so it is difficult to help you more than that. 
Let me know if Sebastian's suggestion does not help you.

**Comment by HotzingTone** [comment]
Thank you very much Mickael!

I will try the solution later and will let you know if that works!

Much appreciate your help!

**Comment by MZehren** [comment]
Good to know, thank you for your input!

I remember having issues with some midi files too. There is already a try/catch [here](https://github.com/MZehren/ADTOF/blob/d718bfdc3e03f461f1ea30d005374a48ccd32922/adtof/converters/converter.py#L268) to count the number of occurrences of each type of errors.

I wonder why yours is not caught already. Maybe it doesn't correspond to a "ValueError".

I'm closing this issue now.
Mickael
