### ISSUE TITLE
ContextualVersionConfilct error when running the second cell of the model

### ISSUE THREAD

**Issue by andreaskal13** [MZehren/ADTOF#16]
Good morning,

I just discovered an issue when I tried to run your model. The error is when running the second cell and is this: 

![image](https://github.com/MZehren/ADTOF/assets/68825475/7108991a-1a7d-47b4-9077-46ebc690074b)

Can you please help me resolve it?

Best regards,
Andreas

**Comment by MZehren** [comment]
Hej Andreas,

I think you need to restart the session, after executing the first cell, when the Colab notebook asks you to do it.
Then click on Runtime>Run all.

Let me know if it works.
Good luck!

**Comment by andreaskal13** [comment]
Hello,


Yes it was fixed!

Thank you very much!
