### ISSUE TITLE
Clarification about the RBMA dataset

### ISSUE THREAD

**Issue by xavriley** [MZehren/ADTOF#17]
There are a couple of references in this repo (and the corresponding paper) to the RBMA dataset. I assume this is the one hosted here:

http://ifs.tuwien.ac.at/~vogl/datasets/

After downloading that data, it looks like there are only three drum classes annotated (BD, SN, HH).

```
/slowfiles/RBMA13-Drums/rbma_13/annotations/drums$ ls *.txt | xargs cut -f 2 | sort | uniq -c
   7369  0
   4513  1
  12483  2
  ```

This repo seems to use a version with [more than 3 classes](https://github.com/MZehren/ADTOF/blob/d87f54777f0275901dffc09364aa4c9d7356a360/adtof/ressources/instrumentsMapping.py#L242) but I can't find any reference to this online. Could you point me in the right direction to find the full annotations please?

**Comment by MZehren** [comment]
Hej Xavier,

This repo seems to use a version with more than 3 classes
> <https://github.com/MZehren/ADTOF/blob/d87f54777f0275901dffc09364aa4c9d7356a360/adtof/ressources/instrumentsMapping.py#L242> but
> I can't find any reference to this online.

You are correct.

Could you point me in the right direction to find the full annotations
> please?
>
You should contact the author of the RBMA dataset, Richard Vogl, to access
the annotations containing more than three classes. Sorry, I don't want to
step on his toes by sharing the annotations myself.

Good luck!

Le lun. 9 sept. 2024 à 14:42, Xavier Riley ***@***.***> a
écrit :

**Comment by xavriley** [comment]
Ah, no worries! I just wanted to check I'm not going crazy 🤪 

I'll contact Richard now 👍
