### ISSUE TITLE
Consider a Python 3 MIDI library

### ISSUE THREAD

**Issue by agzimmerman** [MZehren/ADTOF#3]

**Comment by MZehren** [comment]
Mido seems to be a good candidate to replace midi-python: https://github.com/mido/mido
Unfortunately, it raises errors and crashes with some of the MIDI files containing SYX events.

Those SYX events seem to be badly encoded, as loading and exporting the faulty midi files in Reaper correct the issue in Mido. On the other hand, midi-python just seems to silently discard the badly encoded events, which is not a good idea as silent error handling is not good behaviour.

For now, I'm going to change our dependencies to Mido as it's a more actively developed library. This means that we also need to handle badly encoded MIDI

**Comment by MZehren** [comment]
Issue discussed in mido's repository: https://github.com/mido/mido/issues/187#issuecomment-518741254
